apiVersion: v1
kind: Service
metadata:
  name: fastfood-app
  namespace: desafio-fiap
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: fastfood-app
