spring:
  application:
    name: fast-food-tc

  datasource:
    url: jdbc:mysql://localhost:3306/fastfoodtc # usado para ambiente local
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: drop-and-create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

mercadopago:
  access:
    token: TEST-2693522035727463-051111-593221a6b3646669f028b3794e8b639c-534690741
  webhook:
    base-url: https://huge-musician-87.webhook.cool

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

probe:
  path: /actuator/health
  port: http
  initialDelaySecondsLiveness: 120
  initialDelaySecondsReadness: 120