spring:
  application:
    name: ${SPRING_APPLICATION_NAME:fast-food-tc}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_TOKEN_VALIDATE_URL}/${COGNITO_USER_POOL_ID}

server:
  port: ${SERVER_PORT}

mercadopago:
  access:
    token: ${MERCADOPAGO_ACCESS_TOKEN}
  webhook:
    base-url: ${WEBHOOK_MERCADOPAGO_BASE_URL}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

probe:
  path: /actuator/health
  port: http
  initialDelaySecondsLiveness: 120
  initialDelaySecondsReadness: 120
