apiVersion: v1
kind: Secret
metadata:
  name: fastfood-app-secret
  namespace: desafio-fiap
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=
  MERCADOPAGO_ACCESS_TOKEN: VEVTVC0yNjkzNTIyMDM1NzI3NDYzLTA1MTExMS01OTMyMjFhNmIzNjQ2NjY5ZjAyOGIzNzk0ZThiNjM5Yy01MzQ2OTA3NDE