apiVersion: v1
kind: Secret
metadata:
  name: fastfood-app-secret
  namespace: desafio-fiap
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=
  MERCADOPAGO_ACCESS_TOKEN: TEST-2693522035727463-051111-593221a6b3646669f028b3794e8b639c-534690741